syntax = "proto3";

package group13.depchain;

enum MessageCode {
  NULL       = 0;
  DSMESSAGE  = 1;
  MACMESSAGE = 2;
  COLLECTED  = 3;
  READ       = 4;
}

// All messages will be encapsulated in this
message Message {
  MessageCode code = 1;
  int32 sender     = 2;
  int32 seq        = 3;
  bytes message    = 4;
}

message DSMessage {
  Message message = 1;
  bytes ds        = 2;
}

message MACMessage {
  Message message = 1;
  bytes mac       = 2;
}

message CollectedMessage {
  repeated Message messages = 1;
  repeated bytes sigs       = 2;
}
