syntax = "proto3";

package group13.depchain;

enum MessageCode {
  NULL       = 0;
  DSMESSAGE  = 1;
  MACMESSAGE = 2;
  COLLECTED  = 3;
  READ       = 4;
  WRITE      = 5;
  STATE      = 6;
  ACCEPT     = 7;
  ACK        = 8;
  ABORT      = 9;
}

// All messages will be encapsulated in this
message Message {
  MessageCode code = 1;
  int32 sender     = 2;
  int32 seq        = 3;
  bytes message    = 4;
}

message TransactionMessage {
  string from = 1;
  string to = 2;
  int64 amount = 3;
  int64 nonce = 4;
  bool is_transfer = 5;
  string payload = 6;
  bytes signature = 7;
}

message BlockMessage {
  bytes blockHash = 1;
  bytes previousBlockHash = 2;
  repeated TransactionMessage transactions = 3;
  bool isNullBlock = 4;
}

message WSEntry {
  int32  valts = 1;
  BlockMessage val   = 2;
}

message StateMessage {
  int32 valts               = 1;
  BlockMessage val          = 2;
  repeated WSEntry writeset = 3;
}

message DSMessage {
  Message message = 1;
  bytes ds        = 2;
}

message MACMessage {
  Message message = 1;
  bytes mac       = 2;
}

message CollectedMessage {
  repeated Message messages = 1;
  repeated bytes sigs       = 2;
}
